ElementFitness.App/Pages/Admin/JobApplications/Details.cshtml.cs
using Image = System.IO.File ;
using ElementFitness.BL.Interfaces;
using ElementFitness.Utils.Exceptions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;
using Mapster;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace ElementFitness.App.Pages
{
    [Authorize(Roles = "administrator")]
    public class JobApplicationsDetailAdminViewModel : PageModel
    {
        private readonly IJobApplicantService _jobApplicantService;
        public Models.JobApplicant? JobApplication { get; private set;}


        public JobApplicationsDetailAdminViewModel(
            IJobApplicantService jobApplicantService
            )
        {
            _jobApplicantService = jobApplicantService;
        }

        public async Task<IActionResult> OnGet(int id)
        {
            try
            {
                return RedirectToPage("../PromoVideo"); //remove if you want to enable job detail page
                JobApplication = _jobApplicantService.GetById(id);
                if (JobApplication == null)
                    throw new DatabaseException($"No job application with Id={id} exists.");

                if((bool)!JobApplication.ApplicationRead)
                {
                    JobApplication.ApplicationRead = true;
                    await _jobApplicantService.UpdateAsync(JobApplication);
                }
                   
                return Page();
            }
            catch(Exception ex)
            {
                
                if(ex is DatabaseException)
                    return RedirectToPage("./Index");
                
                Log.Error(ex.Message);
                return RedirectToPage("../../Error");
            }
        }


       public async Task<IActionResult> OnPostDeleteJobListing(int jobApplicationId)
        {
            try
            {
                bool successfullyDeleted = await _jobApplicantService.DeleteAsync(jobApplicationId);
                if (!successfullyDeleted)
                    throw new DatabaseException("An error occurred while deleting the job application. Please try again later.");
                return RedirectToPage("./Index");
            }
            catch(Exception ex)
            {
                if (ex is DatabaseException)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                    return await OnGet(jobApplicationId);
                }

                Log.Error(ex.Message);
                return RedirectToPage("../../Error");
            }
        }
    
    }
}

ElementFitness.App/Pages/Admin/JobListings/Details.cshtml.cs
using Image = System.IO.File ;
using ElementFitness.BL.Interfaces;
using ElementFitness.Utils.Exceptions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;
using Mapster;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace ElementFitness.App.Pages
{
    [Authorize(Roles = "administrator")]
    public class JobListingDetailAdminViewModel : PageModel
    {
        private readonly IJobListingService _jobListingService;
        public Models.Job? Job { get; private set;}

        [BindProperty]
        public Models.Job? UpdatedJob { get; set; }

        public JobListingDetailAdminViewModel(
            IJobListingService jobListingService
            )
        {
            _jobListingService = jobListingService;
        }

        public IActionResult OnGet(int id)
        {
            try
            {
                Job = _jobListingService.GetById(id);
                if (Job == null)
                    throw new DatabaseException($"No job with Id={id} exists.");

                return Page();
            }
            catch(Exception ex)
            {
                
                if(ex is DatabaseException)
                    return RedirectToPage("./Index");
                
                Log.Error(ex.Message);
                return RedirectToPage("../../Error");
            }
        }


        public async Task<IActionResult> OnPostArchiveJobListing(int jobListingId)
        {
            try
            {
                Models.Job? jobListing = _jobListingService.GetById(jobListingId);
                if(jobListing != null)
                {
                    jobListing.Active = false;
                    try
                    {
                        await _jobListingService.UpdateAsync(jobListing);
                        return RedirectToPage("./Index"); 
                    }
                    catch(Exception ex)
                    {
                        throw new DatabaseException("An error occurred while archiving the job listing. Please try again later.");
                    }
                }
                throw new NullReferenceException($"No such job losting exist with the ID = {jobListingId}");
            }
            catch(Exception ex)
            {
                if (ex is DatabaseException || ex is NullReferenceException)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                    Log.Error(ViewData["ErrorMessage"].ToString());
                    return OnGet(jobListingId);
                }

                Log.Error(ex.Message);
                return RedirectToPage("../../Error");
            }
        }

        public async Task<IActionResult> OnPostUnarchiveJobListing(int jobListingId)
        {
            try
            {
                Models.Job? jobListing = _jobListingService.GetById(jobListingId);
                if(jobListing != null)
                {
                    jobListing.Active = true;
                    try
                    {
                        await _jobListingService.UpdateAsync(jobListing);
                        return RedirectToPage("./Index"); 
                    }
                    catch(Exception ex)
                    {
                        throw new DatabaseException("An error occurred while unarchiving the job listing. Please try again later.");
                    }
                }
                throw new NullReferenceException($"No such job losting exist with the ID = {jobListingId}");
            }
            catch(Exception ex)
            {
                if (ex is DatabaseException || ex is NullReferenceException)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                    Log.Error(ViewData["ErrorMessage"].ToString());
                    return OnGet(jobListingId);
                }

                Log.Error(ex.Message);
                return RedirectToPage("../../Error");
            }
        }


        public async Task<IActionResult> OnPostUpdateJob(int id)
        {
            Log.Error(id.ToString());
            try
            {
                Models.Job? jobToBeUpdated = _jobListingService.GetById(id);
                bool? jobstatus = jobToBeUpdated.Active;
                jobToBeUpdated = UpdatedJob.Adapt(jobToBeUpdated);
                jobToBeUpdated.Active = jobstatus;
                bool successfullyUpdated = await _jobListingService.UpdateAsync(jobToBeUpdated);
                if (!successfullyUpdated)
                    throw new DatabaseException("An error occurred while updating the offer. Please refresh the page and try again later.");
                
                
                return RedirectToPage("./Details", new { id });
            }
            catch(Exception ex)
            {
                if (ex is DatabaseException || ex is UploadException)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                    return OnGet(id);
                }

                Log.Error(ex.Message);
                return RedirectToPage("../../Error");
            }
        }

       public async Task<IActionResult> OnPostDeleteJobListing(int jobListingId)
        {
            try
            {
                bool successfullyDeleted = await _jobListingService.DeleteAsync(jobListingId);
                if (!successfullyDeleted)
                    throw new DatabaseException("An error occurred while deleting the enquiry. Please try again later.");
                return RedirectToPage("./Index");
            }
            catch(Exception ex)
            {
                if (ex is DatabaseException)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                    return OnGet(jobListingId);
                }

                Log.Error(ex.Message);
                return RedirectToPage("../../Error");
            }
        }
    
    }
}

ElementFitness.App/Pages/Admin/Partners/Details.cshtml.cs
using Image = System.IO.File ;
using ElementFitness.BL.Interfaces;
using ElementFitness.Utils.Exceptions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;
using Mapster;
using ElementFitness.Models;

namespace ElementFitness.App.Pages
{
    [Authorize(Roles = "administrator")]
    public class PartnerDetailAdminViewModel : PageModel
    {
        private readonly IWebHostEnvironment _environment;
        private readonly string WWWRoot;
        private readonly IPartnerService _partnerService;
        public Partner? Partner { get; private set;}

        [BindProperty]
        public Partner? UpdatedPartner { get; set; }

        public PartnerDetailAdminViewModel(
            IWebHostEnvironment environment, 
            IPartnerService partnerService
            )
        {
            _environment = environment;
            WWWRoot = _environment.WebRootPath;
            _partnerService = partnerService;
        }

        public IActionResult OnGet(int id)
        {
            try
            {
                Partner = _partnerService.GetById(id);
                if (Partner == null)
                    throw new DatabaseException($"No partner with Id={id} exists.");

                return Page();
            }
            catch(Exception ex)
            {
                
                if(ex is DatabaseException)
                    return RedirectToPage("./Index");
                
                Log.Error(ex.Message);
                return RedirectToPage("../../Error");
            }
        }

        public async Task<IActionResult> OnPostUpdatePartner(int id, IFormFile imgToBeUpdated)
        {
            try
            {
                Partner? partnerToBeUpdated = _partnerService.GetById(id);
                partnerToBeUpdated = UpdatedPartner.Adapt(partnerToBeUpdated);
                FileStream stream = null;
                string imgLink = "";
                string file = "";
                if(imgToBeUpdated != null)
                {
                    file = Path.Combine(WWWRoot, $"lib/partners/{Path.GetFileName(partnerToBeUpdated.ImageLink)}");
                    stream = new FileStream(file, FileMode.Open, FileAccess.Read);            
                    try
                    {
                        Image.Delete(file);
                    }
                    catch(Exception ex)
                    { 
                        Log.Error(ex.Message);
                        throw new UploadException("An error occurred while updating the partner. Please try again later."); 
                    }

                    Random randomizer = new Random();
                    string randomizerNumber = "";
                    for(int i = 0; i<3; i++)
                    {
                        randomizerNumber +=  " " + randomizer.NextDouble().ToString(); 
                    }
                    imgLink = Path.Combine(WWWRoot, $"lib/partners/{randomizerNumber}{imgToBeUpdated.FileName}");

                    try
                    {
                        using FileStream fileStream = new FileStream(imgLink, FileMode.Create);
                        await imgToBeUpdated.CopyToAsync(fileStream);
                    }
                    catch(Exception ex)
                    {
                        Log.Error(ex.Message);
                        using FileStream fileStream = new FileStream(file, FileMode.Create);
                        await stream?.CopyToAsync(fileStream);
                        throw new UploadException("An error occurred while updating the partners. Please try again later."); 
                    }
                    partnerToBeUpdated.ImageLink = $"~/lib/partners/{randomizerNumber}{imgToBeUpdated.FileName}";
                }

                bool successfullyUpdated = await _partnerService.UpdateAsync(partnerToBeUpdated);
                if (!successfullyUpdated)
                {
                    if(imgToBeUpdated != null)
                    {
                        Image.Delete(imgLink);
                        using FileStream fileStream = new FileStream(file, FileMode.Create);
                        await stream?.CopyToAsync(fileStream);
                    }
                    throw new DatabaseException("An error occurred while updating the partner. Please refresh the page and try again later.");
                }
                
                return RedirectToPage("./Details", new { id });
            }
            catch(Exception ex)
            {
                if (ex is DatabaseException || ex is UploadException)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                    return OnGet(id);
                }

                Log.Error(ex.Message);
                return RedirectToPage("../../Error");
            }
        }

        public async Task<IActionResult> OnPostDeletePartner(int partnerId)
        {
            try
            {
                Partner partnerToBeDeleted =  _partnerService.GetById(partnerId);
                string? imageLink = partnerToBeDeleted?.ImageLink;
                bool successfullyDeleted = await _partnerService.DeleteAsync(partnerId);
                if (!successfullyDeleted)
                    throw new DatabaseException("An error occurred while deleting the partner. Please try again later.");
                string file = Path.Combine(WWWRoot, $"lib/partners/{Path.GetFileName(imageLink)}");
                Image.Delete(file);
                return RedirectToPage("./Index");
            }
            catch(Exception ex)
            {
                if (ex is DatabaseException)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                    return OnGet(partnerId);
                }

                Log.Error(ex.Message);
                return RedirectToPage("../../Error");
            }
        }
    
    }
}

ElementFitness.App/Pages/Careers/Details.cshtml.cs
using ElementFitness.BL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;

namespace ElementFitness.App.Pages
{
    public class JobDetailViewModel : PageModel
    {
        private readonly IJobListingService _jobListingService;
        public Models.Job? Job { get; private set;}


        public JobDetailViewModel(
            IJobListingService jobListingService
            )
        {
        
            _jobListingService = jobListingService;
        }

        public IActionResult OnGet(int id)
        {
            try
            {
                Job = _jobListingService.GetById(id);
                if (Job == null)
                    return Redirect("./Index");

                return Page();
            }
            catch(Exception ex)
            {
                Log.Error(ex.Message);
                return Redirect("./Index");
            }
        }

    
    }
}

ElementFitness.App/Pages/Partners.cshtml.cs
using ElementFitness.BL.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;

namespace ElementFitness.App.Pages
{
    public class PartnerModel : PageModel
    {

        private readonly IPartnerService _partnerService;
        public IEnumerable<Models.Partner>? Partners { get; private set;}


        public PartnerModel(IPartnerService partnerService)
        {
            _partnerService = partnerService;
        }

        public void OnGet()
        {
            try
            {
                Partners = _partnerService.GetAll();

            }
            catch(Exception ex)
            {
                Log.Error(ex.Message);
            }
        }
    }
}

ElementFitness.App/Pages/Admin/Partners/Details.cshtml
@page "/Admin/Partners/{id:int}"
@model PartnerDetailAdminViewModel
@{
    ViewData["Title"] = "Admin Portal - Partner";
    Layout = "_AdminLayout";
}

<div class="row mt-4">
    <div class="col-6">
        <h1 class="bebas-light">@Model.Partner.Name</h1>
    </div>    
</div>

<div class="d-none">
   <input id="error-message" value="@ViewData["ErrorMessage"]"/>
</div>

<div class="row mt-4">
    <div class="col-12 col-md-6">
        <img src="@Url.Content(@Model.Partner.ImageLink)" id="program-display" class="card-img-top" alt="@Model.Partner.Name image" height="600">
    </div>    
    <div class="col-12 col-md-6 mt-4 mt-md-0">
        @if (!string.IsNullOrWhiteSpace(Model.Partner.Detail))
        {
            <h3 class="bebas-light">Partner Description</h3>
            <p class="normal-text break-word">@Model.Partner.Detail</p>
            <br>
        }

        <div class="row">
            <button class="btn btn-outline-light bebas-light col-4 col-lg-3 me-2" data-bs-toggle="modal" data-bs-target="#update-modal">Update</button>
            <button class="btn btn-outline-light bebas-light col-4 col-lg-3" data-bs-toggle="modal" data-bs-target="#delete-modal">Delete</button>
        </div>
    </div>  
</div>

<!-- Delete Program Modal -->
<div class="modal fade" id="delete-modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="staticBackdropLabel">Delete Partner</h4>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the partner?</p>
      </div>
      <div class="modal-footer">
        <form asp-page-handler="DeletePartner" method="post" >        
            <button type="button" class="btn btn-secondary bebas-light cancel-btn" data-bs-dismiss="modal">Cancel</button>
            <button type="submit" id="modal-delete-btn" name="partnerId" class="btn btn-primary" value="@Model.Partner.PartnerID">Delete</button>             
        </form> 
      </div>
    </div>
  </div>
</div>

<!-- Update Program Modal -->
<div class="modal fade" id="update-modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="staticBackdropLabel">Update Partner</h4>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close" onclick="resetFields('@Model.Partner.Name', '@Model.Partner.Detail')"></button>
      </div>
        <form method="post" asp-page-handler="UpdatePartner" enctype="multipart/form-data">
            <div class="modal-body">
                <div class="form-group">
                    <label asp-for="UpdatedPartner.Name" for="nameInput" class="bebas-light mt-3">Name</label>
                    <input asp-for="UpdatedPartner.Name" type="text" class="form-control" id="nameInput" value="@Model.Partner.Name">
                    <small id="update-name-hint" class="form-text text-muted">@Model.Partner.Name.Length/50 characters</small>
                    <br>
                </div>
                <div class="form-group">
                    <label asp-for="UpdatedPartner.Detail" for="descriptionInput" class="bebas-light mt-3">Description</label>
                    <textarea name="@Html.NameFor(m => m.UpdatedPartner.Detail)" type="text" class="form-control" id="descriptionInput" maxlength="400" rows="4">@Model.Partner.Detail</textarea>
                    <small id="update-description-hint" class="form-text text-muted">@Model.Partner.Detail.Length/400 characters</small>
                </div>         
                <div class="form-group">
                    <label for="DisplayImgInput" class="bebas-light mt-3">Display image</label>
                    <br>
                    <input 
                        type="file" 
                        class="form-control-file" 
                        name="imgToBeUpdated" 
                        id="imgToBeUpdated" 
                        accept="image/*">
                </div>
            </div>
            <div class="modal-footer">
                <button 
                    type="button" 
                    id="update-modal-close-btn" 
                    class="btn btn-secondary bebas-light cancel-btn" 
                    data-bs-dismiss="modal" 
                    onclick="resetFields('@Model.Partner.Name', '@Model.Partner.Detail')">Cancel</button>
                <button type="submit" id="update-modal-update-btn"  class="btn btn-primary">Update Program</button>   
            </div>
        </form>
    </div>
  </div>
</div>


@section Scripts
{
    <script src="~/js/partners.js" asp-append-version="true"></script> 
}

ElementFitness.App/Pages/Admin/Partners/Index.cshtml
@page
@model PartnersIndexAdminViewModel
@{
    ViewData["Title"] = "Admin Portal - Partners";
    Layout = "_AdminLayout";
}

<div class="row">
    <div class="mt-3 col-6 col-md-9 col-lg-10">
        <h1 class="bebas-light">Partners</h1>
    </div>    
    <div class="mt-3 offset-1 col-5 offset-sm-3 col-sm-3 offset-md-0 col-md-3 col-lg-2">
        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#add-modal">Add Partner</button>
    </div>
</div>

<div class="d-none">
   <input id="error-message" value="@ViewData["ErrorMessage"]"/>
</div>

@if (Model!.Partners?.Count() > 0)
{
    <div class="row">
        <div class="col-12">
            <p class="normal-text mt-1">The following partners are being displayed on the website.</p>
        </div>
    </div>
    <div class="row mt-3">
        @foreach(Models.Partner partner in Model.Partners)
        {
            <span class="col-12 col-sm-6 col-md-4 col-lg-3 mt-4">
                <div class="card" >
                    <span class="img-container">
                        <img src="@Url.Content(@partner.ImageLink)" id="program-display" class="card-img-top" alt="@partner.Name image" height="200">
                        <span class="material-symbols-outlined delete-icon" onclick="setOnDeleteParamValue('@partner.PartnerID')"  data-bs-toggle="modal" data-bs-target="#delete-modal">delete</span>
                    </span>
                    <div class="card-body container">
                        <h5 class="card-title  bebas-light row ms-1">@partner.Name</h5>
                        <div class="row ms-1">
                            <a asp-page="/Admin/Partners/Details" asp-route-ID="@partner.PartnerID" class="btn btn-outline-light bebas-light me-1 col-4 col-md-5">View</a>
                            <a asp-page="/Admin/Partners/Details" asp-route-ID="@partner.PartnerID" asp-route-enableEditing="true"  class="btn btn-outline-light bebas-light col-4 col-md-5">Update</a>
                        </div>
                    </div>
                </div>
            </span>
        }
    </div>
}
else
{
    <div class="row mt-3 mt-md-1">
        <div class="col-12">
            <p class="normal-text mt-1">There are no partners added. Your website is not showing any partners currently.</p>
        </div>
    </div>
}


<!-- Add Program Modal -->
<div class="modal fade" id="add-modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="staticBackdropLabel">Add Partner</h4>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close" onclick="resetAddModal()"></button>
      </div>
        <form method="post" asp-page-handler="onPost" enctype="multipart/form-data">
            <div class="modal-body">
                <div class="form-group">
                    <label asp-for="PartnerToBeAdded.Name" for="NameInput" class="bebas-light mt-3">Name*</label>
                    <input asp-for="PartnerToBeAdded.Name" type="text" class="form-control" id="NameInput">
                    <small id="add-name-hint" class="form-text text-muted">0/50 characters</small>
                    <br>
                </div>
                <div class="form-group">
                    <label asp-for="PartnerToBeAdded.Detail" for="DescriptionInput" class="bebas-light mt-3">Description*</label>
                    <textarea asp-for="PartnerToBeAdded.Detail" type="text" class="form-control" id="DescriptionInput" rows="4"></textarea>
                    <small id="add-description-hint" class="form-text text-muted">0/400 characters</small>
                </div> 
                <div class="form-group">
                    <label for="DisplayImgInput" class="bebas-light mt-3">Display image*</label>
                    <br>
                    <input 
                        type="file" 
                        class="form-control-file" 
                        name="displayImg" 
                        id="DisplayImgInput" 
                        accept="image/*">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="add-modal-close-btn" class="btn btn-secondary bebas-light cancel-btn" data-bs-dismiss="modal" onclick="resetAddModal()">Cancel</button>
                <button type="submit" id="add-modal-add-btn" class="btn btn-primary" hidden>Add Partner</button>   
                <button type="submit" id="disabled-add-modal-add-btn" class="btn btn-primary" disabled>Add Partner</button>          
            </div>
        </form>
    </div>
  </div>
</div>

<!-- Delete Program Modal -->
<div class="modal fade" id="delete-modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="staticBackdropLabel">Delete Partner</h4>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the partner?</p>
      </div>
      <div class="modal-footer">
        <form asp-page-handler="DeletePartner" method="post" >        
            <button type="button" class="btn btn-secondary bebas-light cancel-btn" data-bs-dismiss="modal">Cancel</button>
            <button type="submit" id="modal-delete-btn" name="partnerId" class="btn btn-primary">Delete</button>             
        </form> 
      </div>
    </div>
  </div>
</div>



@section Scripts
{
    <script src="~/js/partners.js" asp-append-version="true"></script> 
}